#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "gives all permitions to all files in directiry
optionally gives them also to files in subdirectories-type:	accesgain -R"
fi


if [[ -z $1 ]]
then
	for x in `ls -a`; do sudo chmod +rwx $x 2> /dev/null; done
	chown
	echo "gained acces to all files in directory"
fi

if [[ $1 == "-R" ]]
then
	for x in `ls -a`; do sudo chmod -R +rwx $x 2> /dev/null; done
	echo "gained acces to all files in directory and subdirectories"
fi
