#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "gives all permitions and ownership of all files in directiry
optionally gives them also to files in subdirectories-type:	accesgain -R
for only chmod +x on all files type(non sudo):			accesgain -x"
	exit
fi


privil='rwx'
mode='sudo'
rec=''
#own='sudo chown `whoami` $x'						#whoami nie działa..możliwe, że trzeba tego używać jako #_source
own="sudo chown `pwd | sed 's/\/home\///' | sed 's/\/.*//'` \$x"	#alternatywa z pwd nie będzie działać poza home'm
mess="gained acces and ownership to all files in directory"

if [[ (${1::1} == "-") && (`echo $1 | grep x`) ]] 
then
	privil='x'
	mode=''
	own=''
	mess="gained executable to all files in directory"
fi

if [[ (${1::1} == "-") && (`echo $1 | grep R`) ]]
then
	messR=" and subdirectories"
	rec='-R'
fi

if [[ true ]]
then
	for x in `ls $rec -A`
	do
		if [[ ${x::1} == "." ]]
		then
			continue
		fi
		$mode chmod +$privil $x 2> /dev/null
		eval $own 2> /dev/null
		if [[ $? == "1" ]]
		then
			mess="gained acces(not own-not in home/usr dir-did not write that yet) to all files in directory"
		fi
	done
	echo $mess$messR
fi
