#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "Counts down and sets machine to sleep
type:		asleep \$minuteAmount"
fi

if [[ -z "$1" ]]
then
		echo "parse time(sec)"
fi

#if [[ !( -z $2 ) ]] 
#				#jakbym się chciał bawić w usypianie nie "po czasie", lecz "o godzinie"	

if [[ true ]]
then
	time=$(($1*60))
	for x in `eval echo {1..$time}` 
	do				#rozważyć ewentualny podział na h m s
		clear
		secs=$(($time-$x))	#Świetne narzędzie! Warto do niego jeszcze wrócić:
		printf '%dh:%dm:%ds\n' $(($secs/3600)) $(($secs%3600/60)) $(($secs%60))	
		#echo $(($1-$x))
		sleep 1
	done
	systemctl suspend -i
fi
