#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "was supposed to quickly set and delete crontab jobs NOT FINISHED!!!"
fi


if [ 0 == "$#" ]
then
	echo "brak argumentów"
	exit 1
fi

cmd=""

if [[ ${1:0:1} == "-" ]]
then
	cmd=$2
else
	cmd=$1
fi

function mainFunction {
	#echo "passwd" | sudo -S `echo $cmd >> /etc/crontab`
	sudo `echo $cmd >> /etc/crontab`
}

mainFunction
