#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "eeeem było do nauki, ale za długie żeby zapychać nim bashrc..."
fi

google-chrome file:///home/kuba/Downloads/%23float-fun/%23float-fun%20Jaiswal2017386\(IEEE-TCASI\).pdf file:///home/kuba/Downloads/%23float-fun/%23float-fun%20Matula20152012\(IEEE-TCOMP\),arith,division,+multiplicative.pdf file:///home/kuba/Downloads/%23float-fun/%23float-fun%20DeDinechin201534\(ARITH\),acc,atan2.pdf https://pl.wikipedia.org/wiki/Liczba_zmiennoprzecinkowa#Implementacje_sprz%C4%99towe https://en.wikipedia.org/wiki/Floating-point_arithmetic https://www.google.pl/search?q=Aproksymacja+warto%C5%9Bci+funkcji+w+reprezentacji+zmiennoprzecinkowej&oq=Aproksymacja+warto%C5%9Bci+funkcji+w+reprezentacji+zmiennoprzecinkowej&aqs=chrome..69i57.472j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8 http://zak.ict.pwr.wroc.pl/materials/architektura/wyklad%20AK2/ http://zak.ict.pwr.wroc.pl/materials/architektura/wyklad%20AK2/AK2-4-%20arytmetyka\'17.pdf http://zak.ict.pwr.wroc.pl/materials/architektura/projekt%20AK2/
 
