#!/usr/bin/env bash
#_source

#WARNING: requires xdotool installed!!!

if [[ $1 == "--help" ]]
then
	echo "Connects to first host matching pattern from list kept in .hosts
to see all kept hosts type:	hostcon
to connect to host:		hostcon \$pattern
WARNING: requires xdotool installed!!!"
	return
fi

list=~/scripts/.hosts

if [[ -z $1 ]]
then
	while read -r line
	do
		host=`echo $line | sed 's/=.*//g'`
		echo $host
		comm=`echo $line | sed 's/.*=//'`
		echo $comm
		echo
	done < $list
	return
fi

pattern=$1				#na razie bez żadnych argumentów

if [[ true ]]
then
	while read -r line
	do
		host=`echo $line | sed 's/=.*//'`
		comm=`echo $line | sed 's/.*=//'`
		if [[ `echo $host | grep $pattern` ]]
		then
			if [[ `echo $comm | grep '\-tt'` ]]
			then
				eval $comm
			else
				comm=`echo $comm | sed 's/ssh/ssh -tt/'`
				#eval $comm					#z jakiegoś powodu nie ziała...
				xdotool type "$comm"
				clear
			fi
			break		#exit?
		fi
	done < $list
fi
