#!/usr/bin/env bash


#!!!!!! Dodaj opcję parametr, który włącza grepowi -E(hard regex mode), prawdopodobnie będzie to wymagało kompletnego przerobienia sposobu wywoływania grepa na eval po budowaniu komendy


if [[ $1 == "--help" ]]
then
	echo "script to search recursively in the current directory for files or fileses insides that matches given pattern
type: 					lsd \$pattern_to_look_for
or when searching files insides: 	lsd -f \$pattern
exposing files if dir founded:		lsd -d \$pattern
searching in in put files:		lsd -if \$pattern \$file1 \$file2...

also worth to try like: 		cat \$(lsd [-f] \$pattern) | less 
					cat \$(lsd [-d] \$pattern) | less 
to see all files insides and easly search with \"/\" for multiple occurrence
or:					lsd -if \$inFilePattern \`lsd \$nameFilePattern\` #or other similar searches in \`\` quotes
to research only listed in args files founded by other command"
	exit
fi
if [[ -z $1 ]]
then
	echo "no pattern given, type lsd --help to see more"
	exit
fi

if_sth_founded=0
if [[ -z $2 ]]
then
	pattern=$1
else
	pattern=$2
fi

mssg_not_founded="sorry, no results"


#colored=''					#żeby uwidaczniało te, które pasują idealnie...niby działa, ale jakoś coś chyba za dobrze(czasem)
#if [[ `echo $x | grep -ix $pattern` ]]
#then 
#	colored='tput setaf 1'
#fi
#$colored;echo ${dir::-1}/$x


if [[ (${1::1} == "-") && (`echo $1 | grep [i,f][f,i]`) ]]
then
	shift
	pattern=$1
	shift
	for file in $@
	do
		if [[ `cat $file | grep $pattern` ]]
		then
			echo $file
		fi
	done
	exit
fi



if [[ ( `echo $1 | grep "f"` ) && ( ${1::1} == "-" ) ]]
then
	for x in `ls -pR`
	do  
	        if [[ ${x::1} == '.' ]]
       		then
	                dir=$x
        		continue
		fi
	        if [[ `cat ${dir:0:-1}/$x 2> /dev/null | grep -i "$pattern"` ]]
       		then
	                echo ${dir::-1}/$x
        	        if_sth_founded=1
	        fi
	done
	
	if [[ $if_sth_founded == 0 ]]
	then
	        echo $mssg_not_founded
	fi
	
	exit 0
fi



if [[ ( `echo $1 | grep "d"` ) && ( ${1::1} == "-" ) ]]
then
	for x in `ls -pR`
	do 
		if [[  ( ${x::1} == '.' ) && ( `echo $x | grep -i $pattern` ) ]]
		then
			dir=${x::-1}
			for file in `ls $dir`
			do
				if_sth_founded=1
				if [[ ( ${file::1} != '.' ) && ( ${file: -1} != ':' ) ]]
				then
					echo $dir/$file
				fi
			done
		fi
	done
	
	if [[ $if_sth_founded == 0 ]]
	then
		echo $mssg_not_founded
	fi

	exit 0
fi


if [[ ${1:0:1} != "-" ]]
then
	for x in `ls -pR`
	do 
		if [[ ${x::1} == '.' ]]
		then
			dir=${x::-1}
			continue
		fi
		if [[ `echo $x | grep -i $pattern` ]]
		then
			echo $dir\/$x
			if_sth_founded=1
		fi
	done
	
	if [[ $if_sth_founded == 0 ]]
	then
		echo $mssg_not_founded
	fi

	exit 0
fi
