#!/usr/bin/env bash


if [[ $1 == "--help" ]]
then
	echo "ciastko"
	exit
fi

findBy_disp() {
	comm=''
	ifFirst="true"
	for x in $@
	do
		if [[ !($ifFirst == "true") ]]
		then
			comm="$comm |"
		else
			ifFirst="false"
		fi
	done
}
buildComm() {
	if [[ ${commMode::3} == "EDI" ]]
	then
		comm="changelines -l \$pattern \$prefix \$value \$suffix \$file"
	fi
	if [[ ${commMode::3} == "DEL" ]]
	then
		comm="deletelines -l \$pattern \$file"
	fi
}

fileName="massiveEditPatternFile"
alias changelines='bash ~/scripts/changeLines'
alias deletelines='bash ~/scripts/deletelines'

if [[ !(`ls | grep $fileName`) && !(`ls ~/Documents | grep $fileName`) ]]
then
	echo "no patternFile"
	echo "creating and opening patternFile"
	file="~/Documents/$fileName"
	touch $file
	echo -e "_EDITION\nfindBy:\nx y z\npattern:\np\nprefix:\npx\nvalue:\nv\nsuffix:
sx\npattern:\np2\nprefix2:\npx2\nvalue2:\nv2\nsuffix2:\nsx2\n\nfindBy:\n...\n\n\nDELETION\nfindBy:\nx y z" > $file
	#gedit $file &
	exit
else
	file="./$fileName"
fi

readMode='readVar'
findBy=''
pattern=''
prefix=''
value=''
suffix=''
commMode=''
comm=''

echo $file
if [[ true ]]
then
	
	while read -r line
	do
		if [[ $readMode == "readVar" ]]
		then
			if [[ ${line::1} == "_" ]]
			then
				if [[ -z $commMode ]]
				then
					commMode=`echo ${line:1}`
					continue
				fi
				comm="for file in \``findBy_disp $findBy`\`; do"
				if [[ ${commMode::3} == "EDI" ]]; then comm="deletelines -c;$comm;deletelines -s"; fi
				if [[ ${commMode::3} == "DEL" ]]; then comm="changelines -c;$comm;changelines -s"; fi
				echo $comm
				#eval $comm
				commMode=`echo ${line:1}`
			fi
		fi
	done < $file
fi
