#!/usr/bin/env bash
low=~/Documents/mem_low
hight=~/Documents/mem_hight				#dla ważniejszych rzeczy(dla podziału), do późniejszych updatów

if [[ $1 == "--help" ]]
then
	echo "script acting like an additional cache
to see last input type: 	mem
to see n inputs type:		mem -\$n
to write to memory:		mem \$your_input
to clear cache:			mem -c
to see all cache:		mem -a/all
to see last x lines:		mem -\$x"
fi


touch $low
touch $hight
file=$low
lines=1
args=$*
if [[ $1 == "-h" ]]
then
	file=$hight
fi

if [[ echo $1 | grep '-\d' ]] 				#no nie działa....po prostu za cholerę tego w żaden sposób nie łapie...
then
	$lines=`echo $1 | sed 's/-//'`
	echo złapane
fi



if [[ $1 == "-c" ]]
then
	rm $low $hight
	exit
fi

if [[ ($1 == "-a") || ($1 == "-all") ]]
then
	cat $file | sed 's/;/\n/g'
	echo
	exit
fi

if [[ (-z $1) || ($1 == -[::digit::]) ]]		#no digit nie działa....po prostu za cholerę tego w żaden sposób nie łapie...
then
	cat $file | tail -$lines | sed 's/;/\n/g'
	echo
	exit
fi

if [[ true ]]
then
	echo >> $file
	printf $args | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\;/g' >>  $file
fi
