#!/usr/bin/env bash
#_plsDontUploadMe

if [[ $1 == "--help" ]]
then
	echo "automaticly creates README.md file structure using --help messeges from scripts and .status file
type:	rdmupload"
	exit
fi
	
cd ~/scripts
file=~/scripts/README.md
echo "My bash scripts with a wide range of usabilities" > $file
for script in `git ls-files`
do
	if [[ ($script =~ \..*) || ($script == "$file") ]]
	then
		continue
	fi
	status=`cat .status | grep -e "^$script=.*" | sed 's/.*=//' | sed 's/_.*//'`
	echo >> $file;echo >> $file;echo >> $file
	echo "$script, STATUS=$status" >> $file
	echo >> $file
	echo "Description:" >> $file
	startNr=`cat -n $script | grep '"\-\-help"' | sed 's/if.*//' | sed 's/ //g'`
	startNr=$(($startNr+1))	
	while read -r line
	do
		if [[ $startNr -ge 0 ]]
		then
			if [[ ($startNr -le 0) && ($line =~ .*\"$) ]]; then echo $line | sed 's/echo "//' | sed 's/"$//' >> $file;break;fi
			if [[ $startNr -le 0 ]]; then echo $line | sed 's/echo "//' >> $file;fi
			startNr=$(($startNr-1))	
			continue
		fi
		if [[ $line =~ .*\"$ ]]
		then
			echo $line >> $file
			break
		fi
		echo $line >> $file
	done < $script

	if [[ -z $help ]]
	then
		help="- - -"
	fi
done
