#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "adds all new scripts from ~/scripts/ directory to ~/.bashrc as aliases(script name in lower cases)
basicly if at second line of the script is \"\#_source\" it adds scripts as source"
fi

for x in  `ls ~/scripts`
do
	call='bash'
	if [[ ! `cat ~/.bashrc | grep -i "alias $x="` ]]
	then
		y=`echo "$x" | sed 's/\(.*\)/\L\1/'`
		if [[ `cat ~/scripts/$x | sed -n "2p" | sed 's/.*_//'` == "source" ]]
		then
			call='source'
		fi
		echo "alias $y='$call ~/scripts/$x'" >> ~/.bashrc
		echo "dodano $x"
	fi
done
