#!/usr/bin/env bash


if [[ $1 == "--help" ]]
then
	echo "runs in google-chrome all links from target file(format one linke per line)
type:			session \$filename
for incognito mode:	session \$filename -i"
fi


if [[ $2 == "-i" ]]
then
	comm="google-chrome --incognito "
else
	comm="google-chrome "
fi

for x in `cat $1`
do
	$comm$x
done
