#!/usr/bin/env bash

#w sumie trochę już przestarzałe, bo ogarnąłem na VB opcję wspólnego schowka...
#ale z tą opcją z przesyłaniem plików jeszcze się może przydać bo to szwankuje jeśli robisz to na zasadzie drag&drop

if [[ $1 == "--help" ]]
then
	echo "easy stream between virtual and main system(set your stream localisation to .config as \$STREAM)
type for output:	stream
or:			stream -r
type for input		stream \$args"
	exit
fi

flag='-w'
STREAM=`cat ~/scripts/.config | grep 'STREAM' | sed 's/.*=//'`


#dodać opcję streamu dla plików(wrzuć plik do stream lokalizacji) lub po prostu wyświetl lokalizację STREAM folderu żeby dało się użyć np. `cp $file `stream -l``

if [[ -z $1 ]]
then
	cat $STREAM
	echo
fi

if [[ $1 == "-r" ]]
then 
	cat $STREAM
	echo
fi

if [[ ( ${1:0:1} != "-" ) && ( $1 != "" ) ]]
then
	rm $STREAM
	touch $STREAM
	for arg in $@
	do
		echo -n $arg >> $STREAM
		echo -n " ">> $STREAM
	done
fi

