#!/usr/bin/env bash

if [[ $1 == "--help" ]]
then
	echo "script creates buckup of current dir and unpacks all archives recursively until there will be not more of them
to use type: 	unpackall"
	exit
fi

cont='True'

mkdir backupPacked
for x in `ls | grep -v backupPacked`;do
	cp -R $x backupPacked
done

while [[ $cont == 'True' ]]; do
	cont='False'
	for file in `find . -v '^./backupPacked'`;do
		dir=`echo $file | sed -E 's/\/[^\/]*$/\//g'`
		if [[ $file =~ .*\.zip ]];then
			echo "Unpacking ${file}"
			cont='True'
			unzip $file -d $dir
			if [[ $? != '0' ]];then
				echo "ERROR ocurred!!!"
			fi
			rm $file
		fi
                if [[ $file =~ .*\.tar ]];then
			echo "Unpacking ${file}"
                        cont='True'
                        tar -zxvf $file -C $dir
			if [[ $? != '0' ]];then
				echo "ERROR ocurred!!!"
			fi
                        rm $file
                fi
                if [[ $file =~ .*\.tgz ]];then
			echo "Unpacking ${file}"
                        cont='True'
                        tar -zxvf $file -C $dir
			if [[ $? != '0' ]];then
				echo "ERROR ocurred!!!"
			fi
                        rm $file
                fi
                if [[ $file =~ .*\.txz ]];then
			echo "Unpacking ${file}"
                        cont='True'
                        tar -Jxvf $file -C $dir
			if [[ $? != '0' ]];then
				echo "ERROR ocurred!!!"
			fi
                        rm $file
                fi
	done
done
